[server]
port = 3000
address = "0.0.0.0"
maxUploadSize = 20
runOnSave = true
headless = true

[browser]
serverAddress = "siteplan.atrey-a.com"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true
